api_users_register:
  path: /api/users/register
  controller: App\Controller\Api\UserController::register
  methods: [POST, OPTIONS]

api_users_login:
  path: /api/users/login
  controller: App\Controller\Api\UserController::login
  methods: POST

api_user_me:
  path: /api/users/me
  controller: App\Controller\Api\UserController::me
  methods: GET